export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  PACKED = 'PACKED',
  READY_TO_GO = 'READY_TO_GO',
  AT_CARRIER_FACILITY = 'AT_CARRIER_FACILITY',
  IN_TRANSIT = 'IN_TRANSIT',
  ARRIVED_IN_COUNTRY = 'ARRIVED_IN_COUNTRY',
  AT_LOCAL_FACILITY = 'AT_LOCAL_FACILITY',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

